project:
  type: website

website:
  title: "GAA-Abinav-Test"
  navbar:
    left:
      - text: Hands-on Exercise
        menu:
        - text: Exercise 1
          href: Hands_on_Ex/Hands_onEx01/hands_on_ex01.html
        - text: Exercise 2
          href: Hands_on_Ex/Hands_onEx02/hands_on_ex02.html
        - text: Exercise 3
          href: Hands_on_Ex/Hands_onEx03/hands_on_ex03.html
      - text: Take-home Exercise
        menu:
        - text: "Exercise 1: Executive Summary"
          href: Take_Home_Ex/Take_HomeEx01/take_home_ex01-summary.html
        - text: "Exercise 1: Technical Report"
          href: Take_Home_Ex/Take_HomeEx01/take_home_ex01.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    

editor: visual
