---
title: "Geospatial Data Science with sf"
subtitle: "Hands-on Exercise 1"
date: "today"
date-modified: last-modified
format: html
execute:
  echo: true
  eval: true
  message: false
  warning: false
  freeze: true
editor: visual
toc: true
toc-location: right
---

```{r}
pacman::p_load(sf, tidyverse)
```

```{r}
mpsz = st_read("data/geospatial/MasterPlan2014SubzoneBoundaryNoSea.geojson")

cyclingpath = st_read(dsn = "data/geospatial", 
                       layer = "CyclingPathGazette")

preschool = st_read("data/geospatial/PreSchoolsLocation.geojson")
```

```{r}
mpsz = st_transform(mpsz, crs = 3414)
preschool = st_transform(preschool, crs = 3414)
cyclingpath = st_set_crs(cyclingpath, 3414)
```

```{r}
pacman::p_load(sf, tidyverse)
```

```{r}
mpsz = st_read("data/geospatial/MasterPlan2014SubzoneBoundaryNoSea.geojson")

cyclingpath = st_read(dsn = "data/geospatial", 
                       layer = "CyclingPathGazette")

preschool = st_read("data/geospatial/PreSchoolsLocation.geojson")
```

```{r}
mpsz = st_transform(mpsz, crs = 3414)
preschool = st_transform(preschool, crs = 3414)
cyclingpath = st_set_crs(cyclingpath, 3414)
```

```{r}
st_geometry(mpsz)
glimpse(mpsz)
head(mpsz, n = 5)
```

```{r}
plot(mpsz)
plot(st_geometry(mpsz))
plot(mpsz["PLN_AREA_N"])
```

```{r}
plot(st_geometry(mpsz))
plot(st_geometry(preschool), add = TRUE)
```

```{r}
listings = read_csv("data/aspatial/listings.csv")
list(listings)
```

```{r}
listings_sf = st_as_sf(listings, 
                       coords = c("longitude", "latitude"),
                       crs = 4326) %>%
  st_transform(crs = 3414)

glimpse(listings_sf)
```

```{r}
plot(st_geometry(mpsz))
plot(st_geometry(listings_sf), add = TRUE)
```

```{r}
buffer_cycling = st_buffer(cyclingpath, dist = 5, nQuadSegs = 30)

buffer_cycling = buffer_cycling %>%
  mutate(AREA = st_area(geometry))

sum(buffer_cycling$AREA)
```

```{r}
mpsz_selected = mpsz %>%
  filter(SUBZONE_N == "TAMPINES WEST")

buffer_cycling_selected = st_intersection(buffer_cycling, mpsz_selected)

plot(buffer_cycling_selected)
```

```{r}
mpsz$`PreSch Count` = lengths(st_intersects(mpsz, preschool))

summary(mpsz$`PreSch Count`)

top_n(mpsz, 1, `PreSch Count`)
```

```{r}
mpsz$Area = mpsz %>%
  st_area()

mpsz = mpsz %>%
  mutate(`PreSch Density` = `PreSch Count`/Area * 1000000)
```

```{r}
ggplot(data = mpsz, 
       aes(x = as.numeric(`PreSch Density`))) +
  geom_histogram(bins = 20, 
                 color = "black", 
                 fill = "light blue") +
  labs(title = "Are pre-school even distributed in Singapore?",
       x = "Pre-school density (per km sq)",
       y = "Frequency")
```

```{r}
ggplot(data = mpsz, 
       aes(y = `PreSch Count`, 
           x = as.numeric(`PreSch Density`))) +
  geom_point(color = "black", 
             fill = "light blue") +
  xlim(0, 40) +
  ylim(0, 40) +
  labs(x = "Pre-school density (per km sq)",
       y = "Pre-school count")
```
