---
title: "Hands-on Exercise 2: Thematic Mapping and GeoVisualisation with R"
author: "Abinav"
date: "today"
execute:
  warning: false
---

```{r}
pacman::p_load(sf, terra, spatstat, 
               tmap, rvest, tidyverse)
```

```{r}
mpsz_sf = st_read("data/geospatial/MasterPlan2019SubzoneBoundaryNoSeaGEOJSON.geojson") %>%
  st_zm(drop = TRUE, what = "ZM") %>%
  st_transform(crs = 3414)

childcare_sf = st_read("data/aspatial/ChildCareServices.geojson") %>%
  st_zm(drop = TRUE, what = "ZM") %>%
  st_transform(crs = 3414)
```

```{r}
glimpse(mpsz_sf)
glimpse(childcare_sf)
```

```{r}
mpsz_cl = mpsz_sf %>%
  filter(SUBZONE_N != "SOUTHERN GROUP",
         PLN_AREA_N != "WESTERN ISLANDS",
         PLN_AREA_N != "NORTH-EASTERN ISLANDS")
```

```{r}
write_rds(mpsz_cl, "data/rds/mpsz_cl.rds")
```

```{r}
plot(st_geometry(mpsz_cl))
plot(st_geometry(childcare_sf), add = TRUE, col = "red", pch = 19, cex = 0.5)
```

```{r}
childcare_ppp = as.ppp(childcare_sf)
class(childcare_ppp)
summary(childcare_ppp)
```

```{r}
sg_owin = as.owin(mpsz_cl)
class(sg_owin)
plot(sg_owin)
```

```{r}
childcareSG_ppp = childcare_ppp[sg_owin]
childcareSG_ppp
```

```{r}
clarkevans.test(childcareSG_ppp,
                correction="none",
                clipregion="sg_owin",
                alternative=c("clustered"))
```

```{r}
clarkevans.test(childcareSG_ppp,
                correction="none",
                clipregion="sg_owin",
                alternative=c("clustered"),
                method="MonteCarlo",
                nsim=99)
```

```{r}
kde_SG_diggle = density(
  childcareSG_ppp,
  sigma=bw.diggle,
  edge=TRUE,
  kernel="gaussian")

plot(kde_SG_diggle)
```

```{r}
summary(kde_SG_diggle)
```

```{r}
bw = bw.diggle(childcareSG_ppp)
bw
```

```{r}
childcareSG_ppp_km = rescale.ppp(
  childcareSG_ppp, 1000, "km")

kde_childcareSG_km = density(childcareSG_ppp_km,
                              sigma=bw.diggle,
                              edge=TRUE,
                              kernel="gaussian")

plot(kde_childcareSG_km)
```

```{r}
bw.CvL(childcareSG_ppp_km)
bw.scott(childcareSG_ppp_km)
bw.ppl(childcareSG_ppp_km)
bw.diggle(childcareSG_ppp_km)
```

```{r}
kde_childcareSG.ppl = density(childcareSG_ppp_km, 
                               sigma=bw.ppl, 
                               edge=TRUE,
                               kernel="gaussian")
par(mfrow=c(1,2))
plot(kde_childcareSG_km, main = "bw.diggle")
plot(kde_childcareSG.ppl, main = "bw.ppl")
```

```{r}
par(mar = c(2,2,2,2))
par(mfrow=c(2,2))
plot(density(childcareSG_ppp_km, 
             sigma=0.2959712, 
             edge=TRUE, 
             kernel="gaussian"), 
     main="Gaussian")
plot(density(childcareSG_ppp_km, 
             sigma=0.2959712, 
             edge=TRUE, 
             kernel="epanechnikov"), 
     main="Epanechnikov")
plot(density(childcareSG_ppp_km, 
             sigma=0.2959712, 
             edge=TRUE, 
             kernel="quartic"), 
     main="Quartic")
plot(density(childcareSG_ppp_km, 
             sigma=0.2959712, 
             edge=TRUE, 
             kernel="disc"), 
     main="Disc")
```

```{r}
kde_childcareSG_fb = density(childcareSG_ppp_km,
                              sigma=0.6, 
                              edge=TRUE,
                              kernel="gaussian")
plot(kde_childcareSG_fb)
```

```{r}
kde_childcareSG_ab = adaptive.density(
  childcareSG_ppp_km, 
  method="kernel")
plot(kde_childcareSG_ab)
```

```{r}
par(mfrow=c(1,2))
plot(kde_childcareSG_fb, main = "Fixed bandwidth")
plot(kde_childcareSG_ab, main = "Adaptive bandwidth")
```

```{r}
kde_childcareSG_bw_terra = rast(kde_childcareSG_km)
class(kde_childcareSG_bw_terra)
```

```{r}
kde_childcareSG_bw_terra
```

```{r}
crs(kde_childcareSG_bw_terra) = "EPSG:3414"
kde_childcareSG_bw_terra
```

```{r}
tm_shape(kde_childcareSG_bw_terra) + 
  tm_raster(col.scale = 
              tm_scale_continuous(
                values = "viridis"),
            col.legend = tm_legend(
            title = "Density values",
            title.size = 0.7,
            text.size = 0.7,
            bg.color = "white",
            bg.alpha = 0.7,
            position = tm_pos_in(
              "right", "bottom"),
            frame = TRUE)) +
  tm_graticules(labels.size = 0.7) +
  tm_compass() +
  tm_layout(scale = 1.0)
```

```{r}
pg = mpsz_cl %>%
  filter(PLN_AREA_N == "PUNGGOL")
tm = mpsz_cl %>%
  filter(PLN_AREA_N == "TAMPINES")
ck = mpsz_cl %>%
  filter(PLN_AREA_N == "CHOA CHU KANG")
jw = mpsz_cl %>%
  filter(PLN_AREA_N == "JURONG WEST")
par(mar = c(2,2,2,2))
par(mfrow=c(2,2))
plot(st_geometry(pg), main = "Ponggol")
plot(st_geometry(tm), main = "Tampines")
plot(st_geometry(ck), main = "Choa Chu Kang")
plot(st_geometry(jw), main = "Jurong West")
```

```{r}
clarkevans.test(childcare_ck_ppp,
                correction="none",
                clipregion=NULL,
                alternative=c("two.sided"),
                nsim=999)
```

```{r}
pg = mpsz_cl %>%
  filter(PLN_AREA_N == "PUNGGOL")
tm = mpsz_cl %>%
  filter(PLN_AREA_N == "TAMPINES")
ck = mpsz_cl %>%
  filter(PLN_AREA_N == "CHOA CHU KANG")
jw = mpsz_cl %>%
  filter(PLN_AREA_N == "JURONG WEST")

pg_owin = as.owin(pg)
tm_owin = as.owin(tm)
ck_owin = as.owin(ck)
jw_owin = as.owin(jw)

childcare_pg_ppp = childcare_ppp[pg_owin]
childcare_tm_ppp = childcare_ppp[tm_owin]
childcare_ck_ppp = childcare_ppp[ck_owin]
childcare_jw_ppp = childcare_ppp[jw_owin]
```

```{r}
clarkevans.test(childcare_ck_ppp,
                correction="none",
                clipregion=NULL,
                alternative=c("two.sided"),
                nsim=999)
```

```{r}
clarkevans.test(childcare_tm_ppp,
                correction="none",
                clipregion=NULL,
                alternative=c("two.sided"),
                nsim=999)
```

```{r}
childcare_pg_ppp.km = rescale.ppp(childcare_pg_ppp, 1000, "km")
childcare_tm_ppp.km = rescale.ppp(childcare_tm_ppp, 1000, "km")
childcare_ck_ppp.km = rescale.ppp(childcare_ck_ppp, 1000, "km")
childcare_jw_ppp.km = rescale.ppp(childcare_jw_ppp, 1000, "km")
```

```{r}
par(mar = c(2,2,2,2))
par(mfrow=c(2,2))
plot(density(childcare_pg_ppp.km, 
             sigma=bw.diggle, 
             edge=TRUE, 
             kernel="gaussian"),
     main="Punggol")
plot(density(childcare_tm_ppp.km, 
             sigma=bw.diggle, 
             edge=TRUE, 
             kernel="gaussian"),
     main="Tempines")
plot(density(childcare_ck_ppp.km, 
             sigma=bw.diggle, 
             edge=TRUE, 
             kernel="gaussian"),
     main="Choa Chu Kang")
plot(density(childcare_jw_ppp.km, 
             sigma=bw.diggle, 
             edge=TRUE, 
             kernel="gaussian"),
     main="Jurong West")
```

```{r}
bs = mpsz_cl %>%
  filter(PLN_AREA_N == "BISHAN")

bs_owin = as.owin(bs)

childcare_bs_ppp = childcare_ppp[bs_owin]

childcare_bs_ppp.km = rescale.ppp(childcare_bs_ppp, 1000, "km")

plot(density(childcare_bs_ppp.km, 
             sigma=bw.diggle, 
             edge=TRUE, 
             kernel="gaussian"),
     main="Bishan")
```

```{r}
kde_childcareSG.cvl = density(childcareSG_ppp_km, 
                               sigma=bw.CvL, 
                               edge=TRUE,
                               kernel="gaussian")

par(mfrow=c(1,3))
plot(kde_childcareSG_km, main = "bw.diggle")
plot(kde_childcareSG.ppl, main = "bw.ppl")
plot(kde_childcareSG.cvl, main = "bw.CvL")
```

```{r}
tm_shape(kde_childcareSG_bw_terra) + 
  tm_raster(col.scale = 
              tm_scale_continuous(
                values = "brewer.reds"),
            col.legend = tm_legend(
            title = "Density values",
            title.size = 0.7,
            text.size = 0.7,
            bg.color = "white",
            bg.alpha = 0.7,
            position = tm_pos_in(
              "right", "bottom"),
            frame = TRUE)) +
  tm_graticules(labels.size = 0.7) +
  tm_compass() +
  tm_layout(scale = 1.0)
```

```{r}
set.seed(1234)
```

```{r}
G_CK = Gest(childcare_ck_ppp, correction = "border")
plot(G_CK, xlim=c(0,500))
```

```{r}
G_CK.csr = envelope(childcare_ck_ppp, Gest, nsim = 999)
plot(G_CK.csr)
```

```{r}
G_tm = Gest(childcare_tm_ppp, correction = "best")
plot(G_tm)
```

```{r}
G_tm.csr = envelope(childcare_tm_ppp, Gest, correction = "all", nsim = 999)
plot(G_tm.csr)
```
```{r}
childcare_ck_ppp.km = rescale.ppp(childcare_ck_ppp, 1000, "km")
```

```{r}
kde_ck_adaptive = adaptive.density(
  childcare_ck_ppp.km, 
  method="kernel")

par(mfrow=c(1,2))
plot(density(childcare_ck_ppp.km, 
             sigma=bw.diggle, 
             edge=TRUE, 
             kernel="gaussian"),
     main="Fixed (bw.diggle)")
plot(kde_ck_adaptive, main="Adaptive")
```
```{r}
clarkevans.test(childcare_pg_ppp,
                correction="none",
                clipregion=NULL,
                alternative=c("two.sided"),
                nsim=999)
```

```{r}
clarkevans.test(childcare_jw_ppp,
                correction="none",
                clipregion=NULL,
                alternative=c("two.sided"),
                nsim=999)
```
